#ifndef NEBULA_H
#define NEBULA_H

#include "spaceObject.h"
#include "spaceObjectWithSize.h"

class NebulaCloud
{
public:
    glm::vec2 offset;
    int texture;
    float size;
};
class Nebula : public SpaceObjectWithSize
{
    static PVector<Nebula> nebula_list;
    static const int cloud_count = 32;

    int radar_visual;
    NebulaCloud clouds[cloud_count];

public:
    Nebula();

    virtual float getReasonableMaxValue() override { return 50000; }
    virtual void setSize(float size) override;
    virtual void draw3DTransparent() override;
    virtual void drawOnRadar(sp::RenderTarget& renderer, glm::vec2 position, float scale, float rotation, bool long_range) override;
    virtual void drawOnGMRadar(sp::RenderTarget& renderer, glm::vec2 position, float scale, float rotation, bool long_range) override;
    virtual bool canHideInNebula() override { return false; }
    virtual ERadarLayer getRadarLayer() const override { return ERadarLayer::BackgroundObjects; }

    static bool inNebula(glm::vec2 position);
    static bool blockedByNebula(glm::vec2 start, glm::vec2 end, float radar_short_range);
    static glm::vec2 getFirstBlockedPosition(glm::vec2 start, glm::vec2 end);
    static PVector<Nebula> getNebulas();

    virtual string getExportLine() override { return "Nebula():setPosition(" + string(getPosition().x, 0) + ", " + string(getPosition().y, 0) + "):setSize(" + string(getSize(), 0) + ")"; }

protected:
    glm::mat4 getModelMatrix() const override;
};

// A small PRNG for when reproducability across systems matters (e.g. Nebula clouds).
// Generated by ChatGPT

class PCG32 {
public:
    explicit PCG32(std::uint64_t seed)
        : state_(0), inc_(0xda3e39cb94b95bdbULL)
    {
        next();
        state_ += seed;
        next();
    }

    std::uint32_t next() {
        const std::uint64_t oldstate = state_;

        state_ = oldstate * 6364136223846793005ULL + inc_;

        const std::uint32_t xorshifted =
            static_cast<std::uint32_t>(((oldstate >> 18) ^ oldstate) >> 27);

        const std::uint32_t rot =
            static_cast<std::uint32_t>(oldstate >> 59);

        return (xorshifted >> rot) |
            (xorshifted << ((-rot) & 31));
    }

    float random(float min, float max)
    {
        constexpr float scale = 1.0f / 4294967296.0f; // 2^-32
        const float t = static_cast<float>(next()) * scale;
        return min + (max - min) * t;
    }

    int irandom(int min, int max)
    {
        if (min >= max)
        {
            return min;
        }

        return min + (next() % (max - min + 1));
    }

private:
    std::uint64_t state_;
    std::uint64_t inc_;
};

#endif//NEBULA_H
