SCALE_FACTOR = 2

require("mesh/actioniv.lua")
--require("mesh/bwing.lua")	-- untested/unused
require("mesh/gr75.lua")
require("mesh/hwk290.lua")

model = ModelData()
model:setName("star_destroyer")
model:setMesh("mesh/star_destroyer.obj")
model:setTexture("mesh/star_destroyer_diffuse.png")
model:setIllumination("mesh/star_destroyer_emit.png")
model:setScale(133*2)
model:setRadius(440)
-- len: 1600m

model = ModelData()
model:setName("calamari")
model:setMesh("mesh/calamari.obj")
model:setTexture("mesh/calamari-diffuse.png")
model:setIllumination("mesh/calamari-illumination.png")
model:setScale(4)
model:setRadius(1550)
-- len: 3200m (mc80 home one estimate)

model = ModelData()
model:setName("nebulon_b")
model:setMesh("mesh/nebulon-b.obj")
model:setTexture("mesh/nebulon-b-diffuse.png")
model:setScale(7)
model:setRadius(150)
-- len: 300m

model = ModelData()
model:setName("cr90")
model:setMesh("mesh/cr90.obj")
model:setTexture("mesh/cr90_color.png")
model:setScale(SCALE_FACTOR)
model:setRadius(79 * SCALE_FACTOR)
model:setCollisionBox(150 * SCALE_FACTOR, 48 * SCALE_FACTOR)

model = ModelData()
model:setName("tie_fighter")
model:setMesh("mesh/tie.obj")
model:setTexture("mesh/tie_color.png")
model:setSpecular("mesh/tie_spec.png")
model:setScale(4)
model:setRadius(20)
-- len*width: 7.24m * 6.7m

model:addBeamPosition(1, -0.5, -0.8)
model:addBeamPosition(1,  0.5, -0.8)
model:addTubePosition(1, -0.5, -0.8)
model:addTubePosition(1,  0.5, -0.8)

model = ModelData()
model:setName("tie_interceptor")
model:setMesh("mesh/TieInterceptor.obj")
model:setTexture("mesh/TieInterceptor_color.png")
model:setSpecular("mesh/TieInterceptor_spec.png")
model:setIllumination("mesh/TieInterceptor_illu.jpeg")
model:setScale(4)
model:setRadius(20)
-- 7.7m
model:addBeamPosition(3.5, -2.7, -0.8)
model:addBeamPosition(3.5,  2.7, -0.8)
model:addTubePosition(3.5, -2.7, -0.8)
model:addTubePosition(3.5,  2.7, -0.8)

model = ModelData()
model:setName("tie_bomber")
model:setMesh("mesh/TieBomber.obj")
model:setTexture("mesh/TieBomber_color.png")
model:setSpecular("mesh/TieBomber_spec.png")
model:setIllumination("mesh/TieBomber_illu.jpeg")
model:setScale(5)
model:setRadius(20)
-- 7.8m
model:addBeamPosition(1.4,  0.66, -0.8)
model:addBeamPosition(1.4,  1.3,  -0.8)
model:addTubePosition(1.4,  0.66, -0.8)
model:addTubePosition(1.4,  1.3,  -0.8)
model:addTubePosition(1.8, -1, 0)

model = ModelData()
model:setName("tie_pilot")
model:setMesh("mesh/tie_pilot.obj")
model:setTexture("mesh/tie_pilot_color.jpg")
model:setIllumination("mesh/tie_pilot_illu.png")
model:setScale(3)
model:setRadius(1)
model:setRenderOffset(0, 0, -0.5)

model = ModelData()
model:setName("droid_viper")
model:setMesh("mesh/Droid_Viper.obj")
model:setTexture("mesh/T_Viper_01_CS.png")
model:setScale(750)
model:setRadius(30)


model = ModelData()
model:setName("space_station_4")
model:setMesh("space_station_4/space_station_4.model")
model:setTexture("space_station_4/space_station_4_color.jpg")
model:setSpecular("space_station_4/space_station_4_specular.jpg")
model:setIllumination("space_station_4/space_station_4_illumination.jpg")
model:setRenderOffset(0, 0, 5)
model:setScale(10)
model:setRadius(300)
model:setCollisionBox(400, 400)

model = ModelData()
model:setName("space_station_3")
model:setMesh("space_station_3/space_station_3.model")
model:setTexture("space_station_3/space_station_3_color.jpg")
model:setSpecular("space_station_3/space_station_3_specular.jpg")
model:setIllumination("space_station_3/space_station_3_illumination.jpg")
model:setRenderOffset(10, 0, 5)
model:setScale(20)
model:setRadius(1000)
model:setCollisionBox(1200, 1000)

model = ModelData()
model:setName("space_station_2")
model:setMesh("space_station_2/space_station_2.model")
model:setTexture("space_station_2/space_station_2_color.jpg")
model:setSpecular("space_station_2/space_station_2_specular.jpg")
model:setIllumination("space_station_2/space_station_2_illumination.jpg")
model:setRenderOffset(10, 0, 5)
model:setScale(20)
model:setRadius(1300)
model:setCollisionBox(1400, 1000)

model = ModelData()
model:setName("space_station_1")
model:setMesh("space_station_1/space_station_1.model")
model:setTexture("space_station_1/space_station_1_color.jpg")
model:setSpecular("space_station_1/space_station_1_specular.jpg")
model:setIllumination("space_station_1/space_station_1_illumination.jpg")
model:setRenderOffset(0, 0, 5)
model:setScale(20)
model:setRadius(1500)
model:setCollisionBox(2000, 1800)

model = ModelData()
model:setName("small_fighter_1")
model:setMesh("small_fighter_1.model")
model:setTexture("small_fighter_1_color.jpg")
model:setSpecular("small_fighter_1_specular.jpg")
model:setIllumination("small_fighter_1_illumination.jpg")
model:setScale(3)
model:setRadius(40)

-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(23, 0, -1.8)
model:addEngineEmitter(-8, 0, 0.5,  1.0, 0.2, 0.2, 1.5)


model = ModelData()
model:setName("space_tug")
model:setMesh("space_tug.model")
model:setTexture("space_tug_color.jpg")
--model:setSpecular("space_tug_illumination.jpg")
model:setIllumination("space_tug_illumination.jpg")
model:setScale(6)
model:setRadius(80)

model:addEngineEmitter(-13, -2.1500, 0.3,  0.2, 0.2, 1.0, 3.0)
model:addEngineEmitter(-13,  2.1500, 0.3,  0.2, 0.2, 1.0, 3.0)



model = ModelData()
model:setName("space_frigate_6")
model:setMesh("space_frigate_6.model")
model:setTexture("space_frigate_6_color.png")
model:setSpecular("space_frigate_6_specular.png")
model:setIllumination("space_frigate_6_illumination.png")
model:setScale(6)
model:setRadius(100)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(-1.6, -8, -2)
model:addBeamPosition(-1.6,  8, -2)
model:addTubePosition(18, 0, -3.5)
model:addTubePosition(18, 0, -3.5)
model:addEngineEmitter(-18, 0, -1,  0.2, 0.2, 1.0, 6.0)


model = ModelData()
model:setName("space_cruiser_4")
model:setMesh("space_cruiser_4.model")
model:setTexture("space_cruiser_4_color.jpg")
--model:setSpecular("space_cruiser_4_illumination.jpg")
model:setIllumination("space_cruiser_4_illumination.jpg")
model:setScale(8)
model:setRadius(100)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addTubePosition(2, -10, -2.3)
model:addTubePosition(2,  10, -2.3)
model:addEngineEmitter(-13, -2.1500, 0.3,  0.2, 0.2, 1.0, 3.0)
model:addEngineEmitter(-13, 2.1500, 0.3,  0.2, 0.2, 1.0, 3.0)

model = ModelData()
model:setName("dark_fighter_6")
model:setMesh("dark_fighter_6.model")
model:setTexture("dark_fighter_6_color.png")
model:setSpecular("dark_fighter_6_specular.png")
model:setIllumination("dark_fighter_6_illumination.png")
model:setScale(2)
model:setRadius(56)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(21, -28.2, -2)
model:addBeamPosition(21,  28.2, -2)
model:addEngineEmitter(-28, -1.5, -5,  1.0, 0.2, 0.2, 3.0)
model:addEngineEmitter(-28,  1.5, -5,  1.0, 0.2, 0.2, 3.0)


model = ModelData()
model:setName("battleship_destroyer_1_upgraded")
model:setMesh("battleship_destroyer_1_upgraded/battleship_destroyer_1_upgraded.model")
model:setTexture("battleship_destroyer_1_upgraded/battleship_destroyer_1_upgraded_color.jpg")
model:setSpecular("battleship_destroyer_1_upgraded/battleship_destroyer_1_upgraded_specular.jpg")
model:setIllumination("battleship_destroyer_1_upgraded/battleship_destroyer_1_upgraded_illumination.jpg")
model:setScale(4)
model:setRadius(200)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(34, -17, -7)
model:addBeamPosition(34,  17, -7)
model:addBeamPosition(-5, -33, -1)
model:addBeamPosition(-5,  33, -1)
model:addTubePosition(5, -7, -11)
model:addTubePosition(5,  7, -11)
model:addEngineEmitter(-30, 0, -3,  1.0, 0.2, 0.1, 14.0)
model:addEngineEmitter(-33, 12, -1,  1.0, 0.2, 0.1, 17.0)
model:addEngineEmitter(-33,-12, -1,  1.0, 0.2, 0.1, 17.0)
model:addEngineEmitter(-33, 22, -1,  1.0, 0.2, 0.1, 14.0)
model:addEngineEmitter(-33,-22, -1,  1.0, 0.2, 0.1, 14.0)

model = ModelData()
model:setName("battleship_destroyer_2_upgraded")
model:setMesh("battleship_destroyer_2_upgraded/battleship_destroyer_2_upgraded.model")
model:setTexture("battleship_destroyer_2_upgraded/battleship_destroyer_2_upgraded_color.jpg")
model:setSpecular("battleship_destroyer_2_upgraded/battleship_destroyer_2_upgraded_specular.jpg")
model:setIllumination("battleship_destroyer_2_upgraded/battleship_destroyer_2_upgraded_illumination.jpg")
model:setScale(4)
model:setRadius(200)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(37, -14.5, -3.5)
model:addBeamPosition(37,  14.5, -3.5)
model:addBeamPosition(10, -12, -15)
model:addBeamPosition(10,  12, -15)
model:addBeamPosition(-9, -28, -3)
model:addBeamPosition(-9,  28, -3)
model:addEngineEmitter(-33, 0, -3,  1.0, 0.2, 0.1, 14.0)
model:addEngineEmitter(-36, 14, -4,  1.0, 0.2, 0.1, 17.0)
model:addEngineEmitter(-36,-14, -4,  1.0, 0.2, 0.1, 17.0)

model = ModelData()
model:setName("battleship_destroyer_3_upgraded")
model:setMesh("battleship_destroyer_3_upgraded/battleship_destroyer_3_upgraded.model")
model:setTexture("battleship_destroyer_3_upgraded/battleship_destroyer_3_upgraded_color.jpg")
model:setSpecular("battleship_destroyer_3_upgraded/battleship_destroyer_3_upgraded_specular.jpg")
model:setIllumination("battleship_destroyer_3_upgraded/battleship_destroyer_3_upgraded_illumination.jpg")
model:setScale(4)
model:setRadius(200)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(22,  22, -4.5)
model:addBeamPosition(12, -22, -4.5)
model:addBeamPosition(12,  22, -4.5)

model:addEngineEmitter(-34, 0, 0,  1.0, 0.2, 0.1, 14.0)
model:addEngineEmitter(-36, 13, 0,  1.0, 0.2, 0.1, 17.0)
model:addEngineEmitter(-36,-13, 0,  1.0, 0.2, 0.1, 17.0)

model = ModelData()
model:setName("battleship_destroyer_4_upgraded")
model:setMesh("battleship_destroyer_4_upgraded/battleship_destroyer_4_upgraded.model")
model:setTexture("battleship_destroyer_4_upgraded/battleship_destroyer_4_upgraded_color.jpg")
model:setSpecular("battleship_destroyer_4_upgraded/battleship_destroyer_4_upgraded_specular.jpg")
model:setIllumination("battleship_destroyer_4_upgraded/battleship_destroyer_4_upgraded_illumination.jpg")
model:setScale(4)
model:setRadius(200)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(4, -27, -0.5)
model:addBeamPosition(4,  27, -0.5)
model:addTubePosition(30, -11, -0.5)
model:addTubePosition(30,  11, -0.5)
model:addEngineEmitter(-27, 0, -4,  1.0, 0.2, 0.1, 14.0)
model:addEngineEmitter(-32,-11.5, -1.5,  1.0, 0.2, 0.1, 13.0)
model:addEngineEmitter(-32, 11.5, -1.5,  1.0, 0.2, 0.1, 13.0)
model:addEngineEmitter(-32,-20, -1.5,  1.0, 0.2, 0.1, 10.0)
model:addEngineEmitter(-30, 20, -1.5,  1.0, 0.2, 0.1, 10.0)

model = ModelData()
model:setName("battleship_destroyer_5_upgraded")
model:setMesh("battleship_destroyer_5_upgraded/battleship_destroyer_5_upgraded.model")
model:setTexture("battleship_destroyer_5_upgraded/battleship_destroyer_5_upgraded_color.jpg")
model:setSpecular("battleship_destroyer_5_upgraded/battleship_destroyer_5_upgraded_specular.jpg")
model:setIllumination("battleship_destroyer_5_upgraded/battleship_destroyer_5_upgraded_illumination.jpg")
model:setScale(4)
model:setRadius(200)

-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(-2, -31, -0.5)
model:addBeamPosition(-2,  31, -0.5)
model:addTubePosition(27, 0, -0.5)
model:addTubePosition(27, 0, -0.5)
model:addEngineEmitter(-33, 0, 0,  1.0, 0.2, 0.1, 16.0)
model:addEngineEmitter(-28, 13, -0,  1.0, 0.2, 0.1, 13.0)
model:addEngineEmitter(-28,-13, -0,  1.0, 0.2, 0.1, 13.0)
model:addEngineEmitter(-27, 24, 0,  1.0, 0.2, 0.1, 5.0)
model:addEngineEmitter(-27,-24, 0,  1.0, 0.2, 0.1, 5.0)


model = ModelData()
model:setName("Ender Battlecruiser")
model:setMesh("mesh/ship/Ender Battlecruiser.obj")
model:setTexture("mesh/ship/Ender Battlecruiser.png")
model:setSpecular("mesh/ship/Ender Battlecruiser_illumination.png")
model:setIllumination("mesh/ship/Ender Battlecruiser_illumination.png")
model:setScale(5)
model:setRadius(1000)
model:setCollisionBox(2000, 600)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(66, -71, 12)
model:addBeamPosition(66, -71, -12)
model:addBeamPosition(66,  71, 12)
model:addBeamPosition(66,  71, -12)
model:addBeamPosition(-32, -71, 12)
model:addBeamPosition(-32, -71, -12)
model:addBeamPosition(-32,  71, 12)
model:addBeamPosition(-32,  71, -12)
model:addBeamPosition(-112, -71, 12)
model:addBeamPosition(-112, -71, -12)
model:addBeamPosition(-112,  71, 12)
model:addBeamPosition(-112,  71, -12)
model:addEngineEmitter(-180, -30, 1.2,  0.2, 0.2, 1.0, 30.0)
model:addEngineEmitter(-180,  30, 1.2,  0.2, 0.2, 1.0, 30.0)


model = ModelData()
model:setName("sci_fi_alien_ship_1")
model:setMesh("sci_fi_alien_ship_1/sci_fi_alien_ship_1.model")
model:setTexture("sci_fi_alien_ship_1/sci_fi_alien_ship_1_color.jpg")
model:setSpecular("sci_fi_alien_ship_1/sci_fi_alien_ship_1_specular.jpg")
model:setIllumination("sci_fi_alien_ship_1/sci_fi_alien_ship_1_illumination.jpg")
model:setScale(3)
model:setRadius(180)

model = ModelData()
model:setName("sci_fi_alien_ship_2")
model:setMesh("sci_fi_alien_ship_2/sci_fi_alien_ship_2.model")
model:setTexture("sci_fi_alien_ship_2/sci_fi_alien_ship_2_color.jpg")
model:setSpecular("sci_fi_alien_ship_2/sci_fi_alien_ship_2_specular.jpg")
model:setIllumination("sci_fi_alien_ship_2/sci_fi_alien_ship_2_illumination.jpg")
model:setScale(3)
model:setRadius(180)

model = ModelData()
model:setName("sci_fi_alien_ship_3")
model:setMesh("sci_fi_alien_ship_3/sci_fi_alien_ship_3.model")
model:setTexture("sci_fi_alien_ship_3/sci_fi_alien_ship_3_color.jpg")
model:setSpecular("sci_fi_alien_ship_3/sci_fi_alien_ship_3_specular.jpg")
model:setIllumination("sci_fi_alien_ship_3/sci_fi_alien_ship_3_illumination.jpg")
model:setScale(3)
model:setRadius(150)

model = ModelData()
model:setName("sci_fi_alien_ship_4")
model:setMesh("sci_fi_alien_ship_4/sci_fi_alien_ship_4.model")
model:setTexture("sci_fi_alien_ship_4/sci_fi_alien_ship_4_color.jpg")
model:setSpecular("sci_fi_alien_ship_4/sci_fi_alien_ship_4_specular.jpg")
model:setIllumination("sci_fi_alien_ship_4/sci_fi_alien_ship_4_illumination.jpg")
model:setScale(3)
model:setRadius(150)

model = ModelData()
model:setName("sci_fi_alien_ship_5")
model:setMesh("sci_fi_alien_ship_5/sci_fi_alien_ship_5.model")
model:setTexture("sci_fi_alien_ship_5/sci_fi_alien_ship_5_color.jpg")
model:setSpecular("sci_fi_alien_ship_5/sci_fi_alien_ship_5_specular.jpg")
model:setIllumination("sci_fi_alien_ship_5/sci_fi_alien_ship_5_illumination.jpg")
model:setScale(3)
model:setRadius(150)

model = ModelData()
model:setName("sci_fi_alien_ship_6")
model:setMesh("sci_fi_alien_ship_6/sci_fi_alien_ship_6.model")
model:setTexture("sci_fi_alien_ship_6/sci_fi_alien_ship_6_color.jpg")
model:setSpecular("sci_fi_alien_ship_6/sci_fi_alien_ship_6_specular.jpg")
model:setIllumination("sci_fi_alien_ship_6/sci_fi_alien_ship_6_illumination.jpg")
model:setScale(3)
model:setRadius(150)

model = ModelData()
model:setName("sci_fi_alien_ship_7")
model:setMesh("sci_fi_alien_ship_7/sci_fi_alien_ship_7.model")
model:setTexture("sci_fi_alien_ship_7/sci_fi_alien_ship_7_color.jpg")
model:setSpecular("sci_fi_alien_ship_7/sci_fi_alien_ship_7_specular.jpg")
model:setIllumination("sci_fi_alien_ship_7/sci_fi_alien_ship_7_illumination.jpg")
model:setScale(6)
model:setRadius(330)

model = ModelData()
model:setName("sci_fi_alien_ship_8")
model:setMesh("sci_fi_alien_ship_8/sci_fi_alien_ship_8.model")
model:setTexture("sci_fi_alien_ship_8/sci_fi_alien_ship_8_color.jpg")
model:setSpecular("sci_fi_alien_ship_8/sci_fi_alien_ship_8_specular.jpg")
model:setIllumination("sci_fi_alien_ship_8/sci_fi_alien_ship_8_illumination.jpg")
model:setScale(6)
model:setRadius(350)

model = ModelData()
model:setName("ammo_box")
model:setRadius(50)
model:setMesh("mesh/ammo_box.obj")
model:setTexture("mesh/ammo_box.png")
model:setSpecular("mesh/ammo_box_specular.png")
model:setIllumination("mesh/ammo_box_illumination.png")

model = ModelData()
model:setName("shield_generator")
model:setRadius(150)
model:setScale(3)
model:setMesh("mesh/various/Shield bubble generator.obj")
model:setTexture("mesh/various/Shield bubble generator.jpg")
model:setSpecular("mesh/various/Shield bubble generator specular.jpg")

model = ModelData()
model:setName("small_frigate_1")
model:setMesh("small_frigate_1/small_frigate_1.model")
model:setTexture("small_frigate_1/small_frigate_1_color.png")
model:setSpecular("small_frigate_1/small_frigate_1_specular.png")
model:setIllumination("small_frigate_1/small_frigate_1_illumination.png")
model:setScale(1)
model:setRadius(100)

model:addBeamPosition(100, -36, -3)
model:addBeamPosition(100,  36, -3)
model:addBeamPosition(100, -36, -3)
model:addBeamPosition(100,  36, -3)

model:addEngineEmitter(-85, 33, 2,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-85, 33, 14,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-85,-33, 2,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-85,-33, 14,  0.2, 0.2, 1.0, 8.0)

model = ModelData()
model:setName("small_frigate_2")
model:setMesh("small_frigate_2/small_frigate_2.model")
model:setTexture("small_frigate_2/small_frigate_2_color.png")
model:setSpecular("small_frigate_2/small_frigate_2_specular.png")
model:setIllumination("small_frigate_2/small_frigate_2_illumination.png")
model:setScale(1)
model:setRadius(80)

-- TODO add beam slots here
model:addEngineEmitter(-75, 53,-27,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-75,-53,-27,  0.2, 0.2, 1.0, 8.0)

model = ModelData()
model:setName("small_frigate_3")
model:setMesh("small_frigate_3/small_frigate_3.model")
model:setTexture("small_frigate_3/small_frigate_3_color.png")
model:setSpecular("small_frigate_3/small_frigate_3_specular.png")
model:setIllumination("small_frigate_3/small_frigate_3_illumination.png")
model:setScale(0.8)
model:setRadius(80)

model:addBeamPosition(90, -36, -3)
model:addBeamPosition(90,  36, -3)
model:addBeamPosition(90, -36, -3)
model:addBeamPosition(90,  36, -3)

model:addEngineEmitter(-91, 32,-4,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-95, 32,-17,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-91,-32,-4,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-95,-32,-17,  0.2, 0.2, 1.0, 8.0)

model = ModelData()
model:setName("small_frigate_4")
model:setMesh("small_frigate_4/small_frigate_4.model")
model:setTexture("small_frigate_4/small_frigate_4_color.png")
model:setSpecular("small_frigate_4/small_frigate_4_specular.png")
model:setIllumination("small_frigate_4/small_frigate_4_illumination.png")
model:setScale(1)
model:setRadius(100)

model:addBeamPosition(90, -37, -10)
model:addBeamPosition(90,  37, -10)
model:addBeamPosition(10, -70, -5)
model:addBeamPosition(10,  70, -5)

model:addEngineEmitter(-81, 10,-4,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-81,  0,-4,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-81,-10,-4,  0.2, 0.2, 1.0, 8.0)

model = ModelData()
model:setName("small_frigate_5")
model:setMesh("small_frigate_5/small_frigate_5.model")
model:setTexture("small_frigate_5/small_frigate_5_color.png")
model:setSpecular("small_frigate_5/small_frigate_5_specular.png")
model:setIllumination("small_frigate_5/small_frigate_5_illumination.png")
model:setScale(1)
model:setRadius(80)

model:addBeamPosition(98, -30, -8)
model:addBeamPosition(98,  30, -8)
model:addBeamPosition(98, -30, -8)
model:addBeamPosition(98,  30, -8)

model:addEngineEmitter(-95, 30, 8,  0.2, 0.2, 1.0, 5.0)
model:addEngineEmitter(-95, 30, 0,  0.2, 0.2, 1.0, 5.0)
model:addEngineEmitter(-95, 30,-8,  0.2, 0.2, 1.0, 5.0)
model:addEngineEmitter(-95,-30, 8,  0.2, 0.2, 1.0, 5.0)
model:addEngineEmitter(-95,-30, 0,  0.2, 0.2, 1.0, 5.0)
model:addEngineEmitter(-95,-30,-8,  0.2, 0.2, 1.0, 5.0)

sizes = {
    Fighter={20,30},
    Scout={30,45},
    Corvette={50,80},
    Frigate={75,120},
    Dreadnought={100,160},
    Behemoth={200,260},
}
for sizeName, sizeValues in pairs(sizes) do
  for _, color in ipairs({"Blue", "Green", "Grey", "Red", "White", "Yellow"}) do
    model = ModelData()
    model:setName("AdlerLongRange".. sizeName .. color)
    model:setMesh("AdlerLongRangeScout/AdlerLongRangeSoutHull.model")
    model:setTexture("AdlerLongRangeScout/AlbedoAO/AdlerLongRangeScout"..color.."AlbedoAO.png")
    model:setSpecular("AdlerLongRangeScout/AdlerLongRangeScoutPBRSpecular.png")
    model:setIllumination("AdlerLongRangeScout/AdlerLongRangeScoutIllumination.png")
    model:setScale(sizeValues[1])
    model:setRadius(sizeValues[2])
    -- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
    model:addBeamPosition(1.8, 0, 0.03)
    model:addBeamPosition(1.8,-0.13, 0.03)
    model:addBeamPosition(1.8, 0.13, 0.03)
    model:addTubePosition(1.8,-0.13, 0.03)
    model:addTubePosition(1.8, 0.13, 0.03)
    model:addTubePosition(1.8, 0, 0.03)
    model:addEngineEmitter(-1.5, 0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5, 0.42, 0.33,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, 0.33,  0.5, 0.5, 1.0, 0.5)

    model = ModelData()
    model:setName("AtlasHeavy" .. sizeName .. color)
    model:setMesh("AtlasHeavyFighter/AtlasHeavyFighterHull.model")
    model:setTexture("AtlasHeavyFighter/AlbedoAO/AtlasHeavyFighter"..color.."AlbedoAO.png")
    model:setSpecular("AtlasHeavyFighter/AtlasHeavyFighterPBRSpecular.png")
    model:setIllumination("AtlasHeavyFighter/AtlasHeavyFighterIllumination.png")
    model:setScale(sizeValues[1])
    model:setRadius(sizeValues[2])

    -- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
    model:addBeamPosition(2.4,-0.1, -0.25)
    model:addBeamPosition(2.4, 0.1, -0.25)
    model:addTubePosition(1,-0.4, 0)
    model:addTubePosition(1,-0.4, 0)
    model:addTubePosition(1, 0.4, 0)
    model:addTubePosition(1, 0.4, 0)
    model:addTubePosition(-1, 0, 0) --Mine tube
    model:addEngineEmitter(-1.1, 0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1, 1.05, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-1.05, 0.0,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("AtlasLaser" .. sizeName .. color)
    model:setMesh("AtlasHeavyFighter/AtlasHeavyFighterHull.model")
    model:setTexture("AtlasHeavyFighter/AlbedoAO/AtlasHeavyFighter"..color.."AlbedoAO.png")
    model:setSpecular("AtlasHeavyFighter/AtlasHeavyFighterPBRSpecular.png")
    model:setIllumination("AtlasHeavyFighter/AtlasHeavyFighterIllumination.png")
    model:setScale(sizeValues[1])
    model:setRadius(sizeValues[2])

    --variation with more beams 
    model:addBeamPosition(2.4, 0.0, -0.25)
    model:addBeamPosition(1.0,-0.4,  0.0)
    model:addBeamPosition(1.0, 0.4,  0.0)
    model:addBeamPosition(0.0, -1.2, 0.0)
    model:addBeamPosition(0.0,  1.2, 0.0)
    model:addBeamPosition(-1, 0.0, 0.0)
    model:addTubePosition(-0.5, -1.2, 0)
    model:addTubePosition(-0.5,  1.2, 0)
    model:addTubePosition(-1, 0, 0) --Mine tube
    model:addEngineEmitter(-1.1, 0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1, 1.05, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-1.05, 0.0,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("AtlasMissile" .. sizeName .. color)
    model:setMesh("AtlasHeavyFighter/AtlasHeavyFighterHull.model")
    model:setTexture("AtlasHeavyFighter/AlbedoAO/AtlasHeavyFighter"..color.."AlbedoAO.png")
    model:setSpecular("AtlasHeavyFighter/AtlasHeavyFighterPBRSpecular.png")
    model:setIllumination("AtlasHeavyFighter/AtlasHeavyFighterIllumination.png")
    model:setScale(sizeValues[1])
    model:setRadius(sizeValues[2])

    --variation with side tubes and frontal beams
    model:addBeamPosition(2.4,-0.1, -0.25)
    model:addBeamPosition(2.4, 0.1, -0.25)
    model:addTubePosition(1.8,-0.4, -0.3)
    model:addTubePosition(1.8, 0.4, -0.3)
    model:addTubePosition(-0.5, -1.2, 0)
    model:addTubePosition(-0.5,  1.2, 0)
    model:addTubePosition(-1, 0, 0) --Mine tube
    model:addEngineEmitter(-1.1, 0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1, 1.05, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-1.05, 0.0,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("AtlasCarrier" .. sizeName .. color)
    model:setMesh("AtlasHeavyFighter/AtlasHeavyFighterHull.model")
    model:setTexture("AtlasHeavyFighter/AlbedoAO/AtlasHeavyFighter"..color.."AlbedoAO.png")
    model:setSpecular("AtlasHeavyFighter/AtlasHeavyFighterPBRSpecular.png")
    model:setIllumination("AtlasHeavyFighter/AtlasHeavyFighterIllumination.png")
    model:setScale(sizeValues[1])
    model:setRadius(sizeValues[2])

    -- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
    model:addBeamPosition(2.4,-0.1, -0.25)
    model:addBeamPosition(2.4, 0.1, -0.25)
    model:addTubePosition(1,-0.4, 0)
    model:addTubePosition(1, 0.4, 0)
    model:addTubePosition(-1, 0, 0) --Mine tube
    model:addEngineEmitter(-1.1, 0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1, 1.05, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-1.05, 0.0,  0.5, 0.5, 1.0, 0.4)


    model = ModelData()
    model:setName("Lindwurm" .. sizeName .. color)
    model:setMesh("LindwurmFighter/LindwurmFighterHull.model")
    model:setTexture("LindwurmFighter/AlbedoAO/LindwurmFighter"..color.."AlbedoAO.png")
    model:setSpecular("LindwurmFighter/LindwurmFighterPBRSpecular.png")
    model:setIllumination("LindwurmFighter/LindwurmFighterIllumination.png")
    model:setScale(sizeValues[1])
    model:setRadius(sizeValues[2])

    model:addTubePosition(1.4, 0, 0.06)
    model:addTubePosition(1.4, 0, 0.06)
    model:addTubePosition(1.4, 0, 0.06)
    --model:addTubePosition(0.3,-0.5, 0.06)
    --model:addTubePosition(0.3, 0.5, 0.06)
    model:addEngineEmitter(-1, 0.54, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1,-0.54, 0.0,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("Wespe" .. sizeName .. color)
    model:setMesh("WespeScout/WespeScoutHull.model")
    model:setTexture("WespeScout/AlbedoAO/WespeScout"..color.."AlbedoAO.png")
    model:setSpecular("WespeScout/WespeScoutPBRSpecular.png")
    model:setIllumination("WespeScout/WespeScoutIllumination.png")
    model:setScale(sizeValues[1])
    model:setRadius(sizeValues[2])

    --original: 
    --model:addBeamPosition(1.15,-0.13, -0.03)
    --model:addBeamPosition(1.15, 0.13, -0.03)
    --moved to match radar trace (pos is now outside of the ship)
    model:addBeamPosition(2.15,-1.13, -0.03)
    model:addBeamPosition(2.15, 1.13, -0.03)
    model:addEngineEmitter(-0.2, 0.44, -0.03,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-0.2,-0.44, -0.03,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("Heavy" .. sizeName .. color)
    model:setMesh("HeavyCorvette/HeavyCorvette.model")
    model:setTexture("HeavyCorvette/AlbedoAO/HeavyCorvette"..color.."AlbedoAO.png")
    model:setSpecular("HeavyCorvette/HeavyCorvettePBRSpecular.png")
    model:setIllumination("HeavyCorvette/HeavyCorvetteIllumination.png")
    model:setScale(sizeValues[1])
    model:setRadius(sizeValues[2])

    model:addTubePosition( 0.10, -0.8, 0.0)
    model:addTubePosition(-0.51, -0.8, 0.0)
    model:addTubePosition(-1.10, -0.8, 0.0)
    model:addTubePosition( 0.10,  0.8, 0.0)
    model:addTubePosition(-0.51,  0.8, 0.0)
    model:addTubePosition(-1.10,  0.8, 0.0)
    model:addTubePosition(-1.40, -0.3, 0.0)
    model:addTubePosition(-1.40,  0.3, 0.0)

    model:addEngineEmitter(-1.4, 0.4, 0.0,  0.5, 0.5, 1.0, 0.6)
    model:addEngineEmitter(-1.4, 0.0, 0.0,  0.5, 0.5, 1.0, 0.6)
    model:addEngineEmitter(-1.4,-0.4, 0.0,  0.5, 0.5, 1.0, 0.6)

    model = ModelData()
    model:setName("Laser" .. sizeName .. color)
    model:setMesh("LaserCorvette/LaserCorvette.model")
    model:setTexture("LaserCorvette/AlbedoAO/LaserCorvette"..color.."AlbedoAO.png")
    model:setSpecular("LaserCorvette/LaserCorvettePBRSpecular.png")
    model:setIllumination("LaserCorvette/LaserCorvetteIllumination.png")
    model:setScale(sizeValues[1])
    model:setRadius(sizeValues[2])

    model:addTubePosition(-0.6, -1.0, 0.0)
    model:addTubePosition(-0.6,  1.0, 0.0)
    model:addEngineEmitter(-1.67, 0.1, 0.0,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-1.67,-0.1, 0.0,  0.5, 0.5, 1.0, 0.2)

    model = ModelData()
    model:setName("Light" .. sizeName .. color)
    model:setMesh("LightCorvette/LightCorvette.model")
    model:setTexture("LightCorvette/AlbedoAO/LightCorvette"..color.."AlbedoAO.png")
    model:setSpecular("LightCorvette/LightCorvettePBRSpecular.png")
    model:setIllumination("LightCorvette/LightCorvetteIllumination.png")
    model:setScale(sizeValues[1])
    model:setRadius(sizeValues[2])

    model:addEngineEmitter(-1.3, 0.22, 0.15,  0.5, 0.5, 1.0, 0.3)
    model:addEngineEmitter(-1.3, 0.00, 0.15,  0.5, 0.5, 1.0, 0.3)
    model:addEngineEmitter(-1.3,-0.22, 0.15,  0.5, 0.5, 1.0, 0.3)

    model = ModelData()
    model:setName("MineLayer" .. sizeName .. color)
    model:setMesh("MineLayerCorvette/MineLayerCorvette.model")
    model:setTexture("MineLayerCorvette/AlbedoAO/MineLayerCorvette"..color.."AlbedoAO.png")
    model:setSpecular("MineLayerCorvette/MineLayerCorvettePBRSpecular.png")
    model:setIllumination("MineLayerCorvette/MineLayerCorvetteIllumination.png")
    model:setScale(sizeValues[1])
    model:setRadius(sizeValues[2])

    model:addEngineEmitter(-0.65, 0.70, 0.0,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.65,-0.70, 0.0,  0.5, 0.5, 1.0, 0.2)

    model = ModelData()
    model:setName("Missile" .. sizeName .. color)
    model:setMesh("MissileCorvette/MissileCorvette.model")
    model:setTexture("MissileCorvette/AlbedoAO/MissileCorvette"..color.."AlbedoAO.png")
    model:setSpecular("MissileCorvette/MissileCorvettePBRSpecular.png")
    model:setIllumination("MissileCorvette/MissileCorvetteIllumination.png")
    model:setScale(sizeValues[1])
    model:setRadius(sizeValues[2])

    model:addEngineEmitter(-0.75, 0.24,-0.1,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75, 0.00,-0.1,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75,-0.24,-0.1,  0.5, 0.5, 1.0, 0.2)

    model = ModelData()
    model:setName("MultiGun" .. sizeName .. color)
    model:setMesh("MultiGunCorvette/MultiGunCorvette.model")
    model:setTexture("MultiGunCorvette/AlbedoAO/MultiGunCorvette"..color.."AlbedoAO.png")
    model:setSpecular("MultiGunCorvette/MultiGunCorvettePBRSpecular.png")
    model:setIllumination("MultiGunCorvette/MultiGunCorvetteIllumination.png")
    model:setScale(sizeValues[1])
    model:setRadius(sizeValues[2])

--    model:addBeamPosition(1.18,-0.23, 0.08)
--    model:addBeamPosition(1.18, 0.23, 0.08)
    model:addEngineEmitter(-0.75, 0.2,-0.03,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75, 0.0,-0.03,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75,-0.2,-0.03,  0.5, 0.5, 1.0, 0.2)
  end
end

model = ModelData()
model:setName("SensorBuoyMKI")
model:setMesh("SensorBuoy/SensorBuoyMKI.model")
model:setTexture("SensorBuoy/SensorBuoyAlbedoAO.png")
model:setSpecular("SensorBuoy/SensorBuoyPBRSpecular.png")
model:setScale(300)
model:setRadius(15)

model = ModelData()
model:setName("SensorBuoyMKII")
model:setMesh("SensorBuoy/SensorBuoyMKII.model")
model:setTexture("SensorBuoy/SensorBuoyAlbedoAO.png")
model:setSpecular("SensorBuoy/SensorBuoyPBRSpecular.png")
model:setScale(300)
model:setRadius(15)

model = ModelData()
model:setName("SensorBuoyMKIII")
model:setMesh("SensorBuoy/SensorBuoyMKIII.model")
model:setTexture("SensorBuoy/SensorBuoyAlbedoAO.png")
model:setSpecular("SensorBuoy/SensorBuoyPBRSpecular.png")
model:setScale(300)
model:setRadius(15)

ModelData():setName("artifact1"):setScale(3):setRadius(50):setMesh("mesh/Artifact1.obj"):setTexture("texture/electric_sphere_texture.png")
ModelData():setName("artifact2"):setScale(3):setRadius(50):setMesh("mesh/Artifact2.obj"):setTexture("texture/electric_sphere_texture.png")
ModelData():setName("artifact3"):setScale(3):setRadius(50):setMesh("mesh/Artifact3.obj"):setTexture("texture/electric_sphere_texture.png")
ModelData():setName("artifact4"):setScale(3):setRadius(50):setMesh("mesh/Artifact4.obj"):setTexture("texture/electric_sphere_texture.png")
ModelData():setName("artifact5"):setScale(3):setRadius(50):setMesh("mesh/Artifact5.obj"):setTexture("texture/electric_sphere_texture.png")
ModelData():setName("artifact6"):setScale(3):setRadius(50):setMesh("mesh/Artifact6.obj"):setTexture("texture/electric_sphere_texture.png")
ModelData():setName("artifact7"):setScale(3):setRadius(50):setMesh("mesh/Artifact7.obj"):setTexture("texture/electric_sphere_texture.png")
ModelData():setName("artifact8"):setScale(3):setRadius(50):setMesh("mesh/Artifact8.obj"):setTexture("texture/electric_sphere_texture.png")

for type=1,5 do
    for cnt=1,5 do
        model = ModelData():setName("transport_" .. type .. "_" .. cnt)
        model:setScale(0.5)
        model:setRadius(100 + cnt * 50)
        model:setCollisionBox(200 + cnt * 100, 200)
        model:setMesh("transport_space_ship_" .. type .. "/transport_space_ship_" .. type .. "_cargo_" .. cnt .. ".model")
        model:setTexture("transport_space_ship_" .. type .. "/transport_space_ship_" .. type .. "_color.png")
        model:setSpecular("transport_space_ship_" .. type .. "/transport_space_ship_" .. type .. "_specular.png")
        model:setIllumination("transport_space_ship_" .. type .. "/transport_space_ship_" .. type .. "_illumination.png")
    end
end

-------- Civil cuboid satellite

model = ModelData()
model:setName("cubesat")
model:setMesh("mesh/various/cubesat.obj")
model:setTexture("mesh/various/cubesat.png")
model:setSpecular("mesh/various/cubesat-specular.png")
model:setScale(10)
model:setRadius(100)

model:addEngineEmitter(.7, -.35, 0,  0.2, 0.2, 0.7, 0.5)
model:addEngineEmitter(.7,  .35, 0,  0.2, 0.2, 0.7, 0.5)

-------- Military satellite

model = ModelData()
model:setName("combatsat")
model:setMesh("mesh/various/combatsat.obj")
model:setTexture("mesh/various/combatsat.png")
model:setSpecular("mesh/various/combatsat-specular.png")
model:setScale(10)
model:setRadius(55)
-- Visual positions of the beams/missiletubes (blender: -X, Y, Z)
model:addBeamPosition(2.7,-0.5,0)
model:addBeamPosition(2.7, 0.5,0)
model:addEngineEmitter(-1.5, -.4, 0,  0.2, 0.2, 0.7, 0.5)
model:addEngineEmitter(-1.5,  .4, 0,  0.2, 0.2, 0.7, 0.5)

-------- Debris

model = ModelData()
model:setName("debris-cubesat")
model:setMesh("mesh/various/debris-cubesat.obj")
model:setTexture("mesh/various/cubesat.png")
model:setScale(10)
model:setRadius(100)

model = ModelData():setName("debris-blob")
model:setScale(2):setRadius(100)
model:setMesh("mesh/various/debris-blob.obj")
model:setTexture("mesh/various/debris-blob.jpg")
model:setSpecular("mesh/various/debris-blob-specular.jpg")

-------- Esga ships

model = ModelData()
model:setName("esga_bomber")
model:setMesh("bomber.obj")
model:setTexture("bomber_diffuse.png")
model:setIllumination("bomber_Emissive.png")
model:setSpecular("bomber_spec.png")
model:setScale(12)
model:setRadius(15)
model:addEngineEmitter(-0.84, 0, 0.005,  0.21, .67, .40, 1.0)
model:addBeamPosition(0.52, 0, 0.44)

-- a kraylor variation of the same ship:
model = ModelData()
model:setName("esga_bomber_kraylor")
model:setMesh("bomber.obj")
model:setTexture("bomber_diffuse_kraylor.png")
model:setIllumination("bomber_Emissive_kraylor.png")
model:setSpecular("bomber_spec_kraylor.png")
model:setScale(12)
model:setRadius(15)
model:addEngineEmitter(-0.84, 0, 0.005,  1.0, 0.2, 0.1, 1.0)

model = ModelData()
model:setName("esga_fighter")
model:setMesh("fighter.obj")
model:setTexture("fighter_diffuse.png")
model:setIllumination("fighter_Emissive.png")
model:setSpecular("fighter_spec.png")
model:setScale(12)
model:setRadius(17)
model:addEngineEmitter(-0.97, 0, 0.16,  0.21, .67, .40, 1.0)
model:addBeamPosition(1.33, 0, -0.086)

model = ModelData()
model:setName("esga_droppod")
model:setMesh("droppod.obj")
model:setTexture("droppod_diffuse.png")
model:setIllumination("droppod_Emissive.png")
model:setSpecular("droppod_spec.png")
model:setScale(12)
model:setRadius(17)
model:addEngineEmitter(-1.77, 0, 0.0,  0.21, .67, .40, 1.0)
model:addBeamPosition(1.63, 0, 0)

model = ModelData()
model:setName("esga_construction_drone")
model:setMesh("construction_drone.obj")
model:setTexture("construction_diffuse.png")
model:setIllumination("construction_Emissive.png")
model:setSpecular("construction_spec.png")
model:setScale(12)
model:setRadius(20)
model:addEngineEmitter(-1.25, 0, 0.05,  0.21, .67, .40, 1.0)
model:addBeamPosition(2.31, 0, -0,17)

model = ModelData()
model:setName("esga_corvette_A")
model:setMesh("corvette_A.obj")
model:setTexture("corv_2_diffuse.png")
model:setIllumination("corv_2_Emissive.png")
model:setSpecular("corv_2_spec.png")
model:setScale(12)
model:setRadius(75)
--model:setCollisionBox(75, 23)
model:addEngineEmitter(-4.70, 0, 0.,  0.21, .67, .40, 2.0)

model = ModelData()
model:setName("esga_corvette_B")
model:setMesh("corvette_B.obj")
model:setTexture("corv_1_diffuse.png")
model:setIllumination("corv_1_Emissive.png")
model:setSpecular("corv_1_spec.png")
model:setScale(12)
model:setRadius(72)
--model:setCollisionBox(70, 25)
model:addEngineEmitter(-4.78, 0, 0.055,  0.21, .67, .40, 2.0)

model = ModelData()
model:setName("esga_destroyer_A")
model:setMesh("destroyer_A.obj")
model:setTexture("destroyer_diffuse.png")
model:setIllumination("destroyer_Emissive.png")
model:setSpecular("destroyer_spec.png")
model:setScale(12)
model:setRadius(112)
model:addEngineEmitter(-6.93-0.75, 0, -0.35,  0.21, 0.67, .40, 3.0)
model:addBeamPosition(4.35, -1.21, -1.65)
model:addBeamPosition(4.35,  1.21, -1.65)
model:addBeamPosition(-1.82, -1.72, -0.12)
model:addBeamPosition(-1.82,  1.72, -0.12)
-- heavy beams, very narrow arc, last two can not fire very straight

model = ModelData()
model:setName("esga_destroyer_B")
model:setMesh("destroyer_B.obj")
model:setTexture("destroyer_diffuse.png")
model:setIllumination("destroyer_Emissive.png")
model:setSpecular("destroyer_spec.png")
model:setScale(12)
model:setRadius(105)
model:addEngineEmitter(-6.26-0.75, 0, 0.26,  .21, .67, .40, 3.0)
model:addBeamPosition(7.33, -1.83, 0.29)
model:addBeamPosition(7.33,  1.83, 0.29)
model:addBeamPosition(7.09, -1.83, -0.49)
model:addBeamPosition(7.09,  1.83, -0.49)
model:addBeamPosition(-1.14, -1.72, 0.48)
model:addBeamPosition(-1.14,  1.72, 0.48)
-- light beams, last two can not fire very straight

model = ModelData()
model:setName("esga_destroyer_C")
model:setMesh("destroyer_C.obj")
model:setTexture("destroyer_diffuse.png")
model:setIllumination("destroyer_Emissive.png")
model:setSpecular("destroyer_spec.png")
model:setScale(12)
model:setRadius(115)
model:addEngineEmitter(-7.06-0.75, 0, -0.32,  .21, .67, .40, 3.0)
model:addBeamPosition(-1.95, -1.72, -0.09)
model:addBeamPosition(-1.95,  1.72, -0.09)
-- side mounted - blind spot directly in front

model = ModelData()
model:setName("esga_cruiser_A")
model:setMesh("cruiser_A.obj")
model:setTexture("cruiser_diffuse.png")
model:setIllumination("cruiser_Emissive.png")
model:setSpecular("cruiser_spec.png")
model:setScale(12)
model:setRadius(195)
model:addEngineEmitter(-13.06-0.75, 0, 0.02,  .21, .67, .40, 3.0)
model:addEngineEmitter(-9.82,  3.5, -0.77,  .21, .67, .40, 2.0)
model:addEngineEmitter(-9.82, -3.5, -0.77,  .21, .67, .40, 2.0)
model:addBeamPosition(14.24, -2.09, -0.5)
model:addBeamPosition(14.82,  2.11, -0.5)
model:addBeamPosition(14.99, -1.42, -0.44)
model:addBeamPosition(14.57,  1.44, -0.44)
-- light beams

model = ModelData()
model:setName("esga_cruiser_B")
model:setMesh("cruiser_B.obj")
model:setTexture("cruiser_diffuse.png")
model:setIllumination("cruiser_Emissive.png")
model:setSpecular("cruiser_spec.png")
model:setScale(12)
model:setRadius(204)
model:addEngineEmitter(-12.77-0.75, 0, 0.24,  .21, .67, .40, 3.0)
model:addBeamPosition(15.82, -1.02, 2.4)
model:addBeamPosition(15.82,  0.79, 2.4)
model:addTubePosition(8.31, -0.12, 0.6)
-- launches heavy missiles

model = ModelData()
model:setName("esga_cruiser_C")
model:setMesh("cruiser_C.obj")
model:setTexture("cruiser_diffuse.png")
model:setIllumination("cruiser_Emissive.png")
model:setSpecular("cruiser_spec.png")
model:setScale(12)
model:setRadius(195)
model:addEngineEmitter(-13.28-0.75, 0, 0.24,  .21, .67, .40, 3.0)
model:addEngineEmitter(-10.02,  3.5, -0.55,  .21, .67, .40, 2.0)
model:addEngineEmitter(-10.02, -3.5, -0.55,  .21, .67, .40, 2.0)
model:addBeamPosition(14.94, -0.90, 2.4)
model:addBeamPosition(14.94,  0.92, 2.4)
model:addTubePosition(7.43, 0, 0.61)
model:addTubePosition(0.19, -4.34, 0.67)
model:addTubePosition(0.19,  4.34, 0.67)
-- launches heavy front and light 45° side missiles

model = ModelData()
model:setName("esga_cruiser_D")
model:setMesh("cruiser_D.obj")
model:setTexture("cruiser_diffuse.png")
model:setIllumination("cruiser_Emissive.png")
model:setSpecular("cruiser_spec.png")
model:setScale(12)
model:setRadius(197)
model:addEngineEmitter(-13.24, 0, 0.24,  .21, .67, .40, 2.0)
model:addEngineEmitter(-9.99,  3.5, -0.55,  .21, .67, .40, 2.0)
model:addEngineEmitter(-9.99, -3.5, -0.55,  .21, .67, .40, 2.0)
model:addBeamPosition(12.08, -1.63, 2.0)
model:addBeamPosition(12.08,  1.63, 2.0)
-- heavy beams

model = ModelData()
model:setName("esga_science_ship")
model:setMesh("science_ship.obj")
model:setTexture("science_diffuse.png")
model:setIllumination("science_Emissive.png")
model:setSpecular("sciencevessel_spec.png")
model:setScale(12)
model:setRadius(72)
model:addEngineEmitter(-5.63-1.5, 0, 0.9,  .21, .67, .40, 4.0)
model:addBeamPosition(4.19, -0.65, -0.85)
model:addBeamPosition(4.19,  0.65, -0.85)
model:addBeamPosition(4.30, -1.09, -0.74)
model:addBeamPosition(4.30,  1.09, -0.74)
model:addBeamPosition(0.34, -4.21, -1.46)
model:addBeamPosition(0.34,  4.21, -1.46)
model:addBeamPosition(0.22, -4.70, -1.56)
model:addBeamPosition(0.22,  4.70, -1.56)
-- lots of light beams

model = ModelData()
model:setName("esga_colony_vessel")
model:setMesh("colony_vessel.obj")
model:setTexture("colony_diffuse.png")
model:setIllumination("colony_Emissive.png")
model:setSpecular("colony_spec.png")
model:setScale(12)
model:setRadius(132)
model:addEngineEmitter(-6.93-1.5, 0, -0.8,  .21, .67, .40, 4.0)

model = ModelData()
model:setName("esga_construction_ship")
model:setMesh("construction_ship.obj")
model:setTexture("construction_diffuse.png")
model:setIllumination("construction_Emissive.png")
model:setSpecular("construction_spec.png")
model:setScale(12)
model:setRadius(120)
model:addEngineEmitter(-9.57-1.5, 0, -0.64,  .21, .67, .40, 4.0)
model:addBeamPosition(10.47, -4.18, -0.91)
model:addBeamPosition(10.47,  4.18, -0.91)
model:addBeamPosition(10.23, -4.21, -1.61)
model:addBeamPosition(10.23,  4.21, -1.61)

model = ModelData()
model:setName("esga_transport")
model:setMesh("transport.obj")
model:setTexture("transport_diffuse.png")
model:setIllumination("transport_Emissive.png")
model:setSpecular("transport_spec.png")
model:setScale(12)
model:setRadius(127)
model:addEngineEmitter(-7.20-1.5, 0, -0.54,  .21, .67, .40, 4.0)
model:addBeamPosition(-1.67, -3.93, -0.14)
model:addBeamPosition(-1.67,  3.93, -0.14)
model:addBeamPosition(-1.90, -4.05, -0.72)
model:addBeamPosition(-1.90,  4.05, -0.72)

model = ModelData()
model:setName("esga_juggernaut_carrier")
model:setMesh("juggernaut_carrier.obj")
model:setTexture("juggernaut_diffuse.png")
model:setIllumination("juggernaut_Emissive.png")
model:setSpecular("juggernaut_1k_spec.png")
model:setScale(12)
model:setRadius(260)
model:addEngineEmitter(-19.72-0.75, 0, 1.0,  .21, .67, .40, 3.0)
model:addEngineEmitter(-7.47-0.75,  9.75, -3.0,  .21, .67, .40, 3.0)
model:addEngineEmitter(-7.47-0.75, -9.75, -3.0,  .21, .67, .40, 3.0)
model:addEngineEmitter(-9.52-0.75,  17.25, -8.0,  .21, .67, .40, 3.0)
model:addEngineEmitter(-9.52-0.75, -17.25, -8.0,  .21, .67, .40, 3.0)
model:addBeamPosition(10.51, -55.36, -11.46)
model:addBeamPosition(10.51,  55.36, -11.46)
model:addBeamPosition( 8.77, -53.36, -11.62)
model:addBeamPosition( 8.77,  53.36, -11.62)

model = ModelData()
model:setName("esga_titan_artillery")
model:setMesh("titan_artillery.obj")
model:setTexture("titan_diffuse.png")
model:setIllumination("titan_Emissive.png")
model:setSpecular("titan_spec.png")
model:setScale(12)
model:setRadius(492)
model:addEngineEmitter(-39.23-0.75, 0, 3.18-3.32,  .21, .67, .40, 3.0)
model:addEngineEmitter(-32.41-0.75,  6, -3.83-3.32,  .21, .67, .40, 3.0)
model:addEngineEmitter(-32.41-0.75, -6, -3.83-3.32,  .21, .67, .40, 3.0)
model:addTubePosition(11.67, 0, 3.32-3.32)
model:setRenderOffset(0, 0, -3.32)

-------- Esga stations
model = ModelData()
model:setName("esga_station_citadel")
model:setMesh("citadel.obj")
model:setTexture("citadel_diffuse.png")
model:setIllumination("citadel_Emissive.png")
model:setSpecular("citadel_spec.png")
model:setScale(12)
model:setRadius(280)
model:setRenderOffset(0, 0, -1.2)

model = ModelData()
model:setName("esga_station_habitat")
model:setMesh("habitat.obj")
model:setTexture("habitat_diffuse.png")
model:setIllumination("habitat_Emissive.png")
model:setSpecular("habitat_spec.png")
model:setScale(12)
model:setRadius(295)
model:setRenderOffset(0, 0, -6.5)

model = ModelData()
model:setName("esga_station_starbase")
model:setMesh("starbase.obj")
model:setTexture("starbase_diffuse.png")
model:setIllumination("starbase_Emissive.png")
model:setSpecular("starbase_spec.png")
model:setScale(12)
model:setRadius(145)
model:setRenderOffset(0, 0, -8.8)

model = ModelData()
model:setName("esga_station_assemblyyard")
model:setMesh("assemblyyard_module.obj")
model:setTexture("assemblyyard_diffuse.png")
model:setIllumination("assemblyyard_Emissive.png")
model:setSpecular("assemblyyard_spec.png")
model:setScale(12)
model:setRadius(130)
model:addEngineEmitter(-10.86, 0, 0.69,  .21, .67, .40, 2.0)
model:addBeamPosition(5.27, 0, -3.58)
model:addBeamPosition(10.63, -3.88, 0.72)
model:addBeamPosition(10.63,  3.88, 0.72)

model = ModelData()
model:setName("esga_station_habitation")
model:setMesh("habitation_module.obj")
model:setTexture("habitation_module_diffuse.png")
model:setIllumination("habitation_module_Emissive.png")
model:setSpecular("habitation_spec.png")
model:setScale(12)
model:setRadius(132)
model:addEngineEmitter(-9.04, 0, -0.46-2.0,  .21, .67, .40, 2.0)
model:setRenderOffset(0, 0, -2.0)

model = ModelData()
model:setName("esga_station_hangar")
model:setMesh("hangar_module.obj")
model:setTexture("hangar_module_diffuse.png")
model:setIllumination("hangar_module_Emissive.png")
model:setSpecular("hangar_spec.png")
model:setScale(12)
model:setRadius(120)
model:addEngineEmitter(-8.77, 0, -0.15,  .21, .67, .40, 2.0)

model = ModelData()
model:setName("esga_station_mining")
model:setMesh("mining_module.obj")
model:setTexture("mining_module_diffuse.png")
model:setIllumination("mining_module_Emissive.png")
model:setSpecular("mining_spec.png")
model:setScale(12)
model:setRadius(137)
model:addEngineEmitter(-10.19, 0, -1.69,  .21, .67, .40, 2.0)
model:addBeamPosition(9.21,  7.06, -1.21)
model:addBeamPosition(9.21, -7.06, -1.21)

model = ModelData()
model:setName("esga_station_science")
model:setMesh("science_module.obj")
model:setTexture("science_module_diffuse.png")
model:setIllumination("science_module_Emissive.png")
model:setSpecular("science_spec.png")
model:setScale(12)
model:setRadius(117)
model:addEngineEmitter(-8.25, 0, 0.64,  .21, .67, .40, 2.0)
model:addBeamPosition(3.89, -8.28, 0.76)
model:addBeamPosition(3.89,  8.28, 0.76)


